version: "3.1"

services:
  bill-one-2024-postgres:
    # recipientとsender共通のDB
    # https://cloud.google.com/sql/docs/postgres/db-versions?hl=ja
    image: "postgres:15"
    volumes:
      - "bill-one-2024-postgres-data:/var/lib/postgresql/data"
      - "./dockerfiles/postgres/initdb:/docker-entrypoint-initdb.d"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust

  # From: https://github.com/fsouza/fake-gcs-server
  # senderとrecipientの間でファイルをやり取りするためのストレージ
  cloud-storage-emulator:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    volumes:
      - "./dockerfiles/gcloud-storage-emulator/preload:/data"
      - "bill-one-2024-cloud-storage:/storage"
    command: -scheme http --public-host localhost --external-url localhost:4443

  # senderとrecipientの間でやり取りするためのtasks
  gcloud-tasks-emulator:
    build: dockerfiles/gcloud-tasks-emulator
    platform: 'linux/amd64'
    ports:
      - "9090:9090"
    command:
      [
        "start",
        "--port=9090",
        "--default-queue=projects/bill-one-2024/locations/asia-northeast1/queues/issuing",
        "--default-queue=projects/bill-one-2024/locations/asia-northeast1/queues/recipient",
        "--max-retries=1",
      ]

  # gcloud-tasks-emulatorのコンテナから localhost:8081 でDockerホスト（Mac）上の8081ポートにアクセスするためのハック
  socat-8081:
    image: alpine/socat
    command:
      [
        "-d",
        "tcp-listen:8081,fork,reuseaddr",
        "tcp-connect:host.docker.internal:8081",
      ]
    network_mode: "service:gcloud-tasks-emulator"
  # gcloud-tasks-emulatorのコンテナから localhost:8082 でDockerホスト（Mac）上の8082ポートにアクセスするためのハック
  socat-8082:
    image: alpine/socat
    command:
      [
        "-d",
        "tcp-listen:8082,fork,reuseaddr",
        "tcp-connect:host.docker.internal:8082",
      ]
    network_mode: "service:gcloud-tasks-emulator"
    # gcloud-tasks-emulatorのコンテナから localhost:8400 でDockerホスト（Mac）上の8400ポートにアクセスするためのハック
  socat-8400:
    image: alpine/socat
    command:
      [
        "-d",
        "tcp-listen:8400,fork,reuseaddr",
        "tcp-connect:host.docker.internal:8400",
      ]
    network_mode: "service:gcloud-tasks-emulator"

#  socat-4443:
#    image: alpine/socat
#    command:
#      [
#        "-d",
#        "tcp-listen:4443,fork,reuseaddr",
#        "tcp-connect:host.docker.internal:4443",
#      ]

volumes:
  bill-one-2024-postgres-data:
    driver: local
  bill-one-2024-cloud-storage:
    driver: local